// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzskyeufhxumkmjijkkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6c2t5ZXVmaHh1bWttamlqa2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjkzNzMsImV4cCI6MjA2MDI0NTM3M30.HZUlo_U2fS_oIHezVNhcN5erjqeRlP2RJUBhFc3n6V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);